# ----------------------------------------
# PROPERTIES MOCK
# ----------------------------------------

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------
server.servlet.application-display-name=@project.parent.artifactId@
server.port=8080
server.servlet.context-path=/@project.parent.artifactId@
spring.mvc.servlet.path=/

jetty.accesslog.path=./logs
server.jetty.accesslog.filename=${jetty.accesslog.path}/jetty_access.log

# ----------------------------------------
# DATASOURCE PROPERTIES
# ----------------------------------------
spring.jpa.generate-ddl=true
spring.data.jpa.repositories.enabled=true

# ----------------------------------------
# SECURITY CONFIGURATION
# ----------------------------------------
security.authentication.jwt.secret=my-secret-token-for-@project.parent.artifactId@-should-be-512-bits-size-and-change-for-production
security.authentication.jwt.tokenValidityInSeconds=86400
spring.ldap.username=[LDAP_USER]
spring.ldap.password=[LDAP_PASSWORD]
security.rolesConfig.projectRoles=AUTHENTICATED
security.enable-csrf=false

# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
security.rolesConfig.actuatorRoles=NOT_AUTHENTICATED

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------
logging.config=classpath:logback-spring.xml

# ----------------------------------------
# COMPLEMENTARY MANAGEMENT WS
# ----------------------------------------
info.app.custom.projectCode=MANDATORY:CODE APP CARTO
info.app.custom.projectName=@project.parent.artifactId@
info.app.custom.projectDesc=@project.parent.description@
info.app.custom.projectVersion=@project.parent.version@
info.app.custom.environment=mock
info.app.custom.hostname=localhost
info.app.custom.serverPort=${server.port}

# ----------------------------------------
# SPRING DEVTOOLS CONFIGURATION
# ----------------------------------------
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false

# ----------------------------------------
# MOCK CONFIGURATOR PROPERTIES
# ----------------------------------------
configurator.service.url=http://localhost:8081
external.api.soprano-configurateur.url=http://toto/soprano-produit-api
